=== IsaacSxm/flight_RestfulApi/Schemas/xml/Airlines.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

<xs:element name="Airlines">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="Airline" type="AirlineDetails" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:complexType name="AirlineDetails">
    <xs:sequence>
        <xs:element name="Airline_id" type="length" maxOccurs="1"/>
        <xs:element name="Airline" type="xs:string" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
</xs:complexType>


    <xs:simpleType name="length">
        <xs:restriction base="xs:string">
            <xs:whiteSpace value="collapse"/>
            <xs:length value="2"/>
        </xs:restriction>
    </xs:simpleType>



</xs:schema>

=== IsaacSxm/flight_RestfulApi/Schemas/xml/Airlines.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Airlines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Airlines.xsd">
    <Airline>
        <Airline_id>UA</Airline_id>
        <Airline>United Air Lines Inc.</Airline>
    </Airline>
    <Airline>
        <Airline_id>AA</Airline_id>
        <Airline>American Airlines Inc.</Airline>
    </Airline>
    <Airline>
        <Airline_id>AWSDE</Airline_id>
        <Airline>Ney York Airline</Airline>
    </Airline>
</Airlines>
