=== IsaacSxm/flight_RestfulApi/Schemas/xml/Airport.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

<xs:element name="Airports">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="Airport" type="AirportDetails" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
    
<xs:complexType name="AirportDetails">
    <xs:sequence>
        <xs:element name="Airport_id" type="Airport_id" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Airport_Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="City" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="State" type="State" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Country" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Latitude" type="xs:decimal" minOccurs="1" maxOccurs="1"/>
        <xs:element name="Longitude" type="xs:decimal" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
</xs:complexType>
    
    <xs:simpleType name="Airport_id">
        <xs:restriction base="xs:string">
            <xs:whiteSpace value="collapse"/>
            <xs:length value="3"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="State">
        <xs:restriction base="xs:string">
            <xs:whiteSpace value="collapse"/>
            <xs:length value="2"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== IsaacSxm/flight_RestfulApi/Schemas/xml/Airport.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Airports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Airport.xsd">
    <Airport>
        <Airport_id>ABE</Airport_id>
        <Airport_Name>Lehigh Valley International Airport</Airport_Name>
        <City>Allentown</City>
        <State>PA</State>
        <Country>USA</Country>
        <Latitude>40.65236</Latitude>
        <Longitude>-75.44040</Longitude>
    </Airport>
    <Airport>
        <Airport_id>ABI</Airport_id>
        <Airport_Name>Abilene Regional Airport</Airport_Name>
        <City>Abilene</City>
        <State>TX</State>
        <Country>USA</Country>
        <Latitude>32.41132</Latitude>
        <Longitude>-99.68190</Longitude>
    </Airport>
</Airports>
